### ISSUE TITLE
No scrollbar for folder list?

### ISSUE THREAD

**Issue by eggfriedrice** [YouweGit/FileManager#2]
A long list of files in the file pane will create a scrollbar on the right, but the same doesn't seem to happen for the folder list so if I have a long directory tree I can't get to the ones at the bottom.

Is this a bug or have I screwed up something here?

**Comment by EazyAlvaro** [comment]
Probably a CSS bug on our end, i will poke the person responsible.

**Comment by eggfriedrice** [comment]
Great, thanks!

**Comment by jimmy626ooip** [comment]
Hi @eggfriedrice,

Thank you for reporting this CSS issue. I have updated the bundle. You will now get a scrollbar when you have a long directory tree.

Can you confirm it if its fixed?

**Comment by alexraileanu** [comment]
closed for inactivity.
