### ISSUE TITLE
Bug in FileManager.php

### ISSUE THREAD

**Issue by oscaramidasoft** [YouweGit/FileManager#5]
At line 300, we can find this code:
           if (strcasecmp($real_path, $upload_path > 0)) {

It should be:
        if (strcasecmp($real_path, $upload_path) > 0) {

I would correct it, but I don't know how to push changes...

**Comment by PascalBrouwers** [comment]
@jimmy6262 Good find of this guy, maybe you can add his change? :)

**Comment by oscaramidasoft** [comment]
I'm new to GitHub, how could I add this?

**Comment by PascalBrouwers** [comment]
Well, you can make a Fork of this repo. Clone your Fork, make the change on your machine. Then push it and create a pull request.

**Comment by oscaramidasoft** [comment]
I did it!
It is my first contrib to a Github project!

**Comment by alexraileanu** [comment]
PR's been accepted and merged.
